language: node_js

node_js: "8"

notifications:
  slack:
    secure: Klm1awhorcCXDSfFd9onFYiSiJw7T/9x841Cw+aElKXjZSITxhX+erSsmLLiRNuBxn0/ZanADbK8jxE/wpmQ9dqmvCU8QaFmBZI6qvQwhHhbvohYjC/rbwQJIzQyxSQ8oL7HVVF+r3CLQKax7NA8Ivip5hppWixd8RaqT+DRhaYkjh9IEsDsagVGl6u716mjkcv2IR/KE6Xs1dylx9m7Bwxi2Ukboc8kokY2Bgn64WVuPZfarAlJRor88HourhfEQwbcZme35OpTIG/u/uDYxqX4VYqq6VjFlNyOAU+8wdDpuH8NbNeBtxmkjUol38RcL/nNMKxQc0ilFJF+RmJ5cBfReS7ZWD8rpEHDr9PtAgPxeAnu198xGLIIVGdu8vHeMyi95uoW1CSTxiz2olpsslVXnCDzm6kKNb7VWlnQpYDusWcuDUA862O33iMejqRVWWU61o2MfrF1afhQwNkVGIl5zkLKONLyFT4lmnygHW0v7ZVakymiZdjejXbDzYtSu8kPDHtVkojcdKSUUROFHxQYlbm35XT+2YS3G8V+ZvfU72gnDc9ry5b3BNLUs37bEmPjiyi9SPDNo7YG+Dle+dJxUf5MjgpFlJsqwmaiuqXvYKE7KfRBZ8vw/O4CwwUbSf/RvY6o4byGvoYlVvy3d/0k20SKOuYq8kaa8YgV9Yo=
  email: false

