language: node_js

node_js: "9"

services: docker

env:
  global:
    - FROMTAG=39f5ed02690ccde1a7458f900a9e84fafb98d432

after_success:
  - docker build -t blogapi.azurecr.io/blog-api .
  - docker run -d -p 80:80 blog-api
  - docker ps -a
  - wget --retry-connrefused --waitretry=1 http://127.0.0.1:80
  - tar -xzvf deploy.tar.gz

deploy:
  - provider: script
    on:
      branch: master
    script: bash deploy.sh
    skip_cleanup: true
